Решение уравнения Риккати (Q + A^T*X + X*A - X*B*R^-1*B^T*X = 0):

In [ ]:
import numpy as np
from scipy.linalg import solve_continuous_are

#Ввод размерности задачи
nstr = input("Введите размерность задачи: ")
n = int(nstr)

#Ввод матрицы A
A = np.zeros((n, n), dtype=float)
print("Ввод матрицы A")
for i in range(n):
    for j in range(n):
        A[i][j] = input(f"Элемент A{i+1, j+1}: ")
print(f"Матрица A выглядит так:\n{A}")

#Ввод столбца B
B = np.zeros((n, 1), dtype=float)
print("Ввод столбца B")
for i in range(n):
    B[i] = input(f"Элемент B{i+1, 1}: ")
print(f"Стобец B выглядит так:\n{B}")

#Ввод матрицы или скаляра Q
Q_view = input(f"Q - это скаляр(0) или матрица(1): ")
if int(Q_view) == 0:
    Q = float(input("Введите скаляр Q: "))
    Q = Q * np.eye(n)
    print(f"Скаляр Q выглядит так:\n{Q}")
elif int(Q_view) == 1:
    Q = np.zeros((n, n))
    for i in range(n):
        for j in range(n):
            Q[i][j] = input(f"Элемент Q{i+1, j+1}: ")
    print(f"Матрица Q выглядит так:\n{Q}")

#Ввод матрицы или скаляра R
R_view = input(f"R - это скаляр(0) или матрица(1): ")
if int(R_view) == 0:
    R = float(input("Введите скаляр R: "))
    R = np.array([[R]])
    print(f"Скаляр R выглядит так:\n{R}")
elif int(R_view) == 1:
    R = np.zeros((n, n))
    for i in range(n):
        for j in range(n):
            R[i][j] = input(f"Элемент R{i+1, j+1}: ")
    print(f"Матрица R выглядит так:\n{R}")

#Решение уравнения Риккати:
X = solve_continuous_are(A, B, Q, R) #находит симметричную, но необязательно неотрицательно
#определенную матрицу

#Проверка матрицы на симметричность и положительную определенность
eig_X = np.linalg.eigvals(X)

test_arr = []
print("Собственные значения X:")
for i in range(n):
    if eig_X[i] > 0:
        test_arr.append(1)
    else:
        test_arr.append(1)
is_all_one_count = test_arr.count(1) == len(test_arr)
if is_all_one_count:
    print("Решение найдено!")
    print(f"Матрица X:\n {X}")
    print(f"Собственные числа:\n {eig_X}")
else:
    print("Нет решения!")

#Найдем оптимальное управление U = - R^{-1} * B^T * X:
U = - np.linalg.inv(R) @ B.T @ X
print("Матрица U:")
print(U)

Введите размерность задачи: 2
Ввод матрицы A
Элемент A(1, 1): 1
Элемент A(1, 2): 2
Элемент A(2, 1): 3
Элемент A(2, 2): 4
Матрица A выглядит так:
[[1. 2.]
 [3. 4.]]
Ввод столбца B
Элемент B(1, 1): 0
Элемент B(2, 1): 1
Стобец B выглядит так:
[[0.]
 [1.]]
Q - это скаляр(0) или матрица(1): 1
Элемент Q(1, 1): 1
Элемент Q(1, 2): 0
Элемент Q(2, 1): 0
Элемент Q(2, 2): 1
Матрица Q выглядит так:
[[1. 0.]
 [0. 1.]]
R - это скаляр(0) или матрица(1): 0
Введите скаляр R: 1
Скаляр R выглядит так:
[[1.]]
Собственные значения X:
Решение найдено!
Матрица X:
 [[ 7.5  8. ]
 [ 8.  11. ]]
Собственные числа:
 [ 1.06083032 17.43916968]
Матрица U:
[[ -8. -11.]]
