Решение уравнения Риккати для дискретной системы: 
Q + A^T*X - A^T*X*B*(B^T*X*B + R)^-1*B^T*X*A-X=0

Правило работы с данной программой:
1) Понять в задаче матрицы A, B и посмотреть наличие управляемости через ранг матрицы управляемости
2) Понять в задаче матрицы Q, R и вычислить C (Q = C^T * C), затем посмотреть наличие наблядаемости или детектируемости системы
3) Вбить эти данные в программу и радоваться результату!

In [ ]:
import numpy as np
from scipy.linalg import solve_discrete_are

#Ввод размерности задачи
nstr = input("Введите размерность задачи: ")
n = int(nstr)

#Ввод матрицы A
A = np.zeros((n, n), dtype=float)
print("Ввод матрицы A")
for i in range(n):
    for j in range(n):
        A[i][j] = input(f"Элемент A{i+1, j+1}: ")
print(f"Матрица A выглядит так:\n{A}")

#Ввод столбца B
B = np.zeros((n, 1), dtype=float)
print("Ввод столбца B")
for i in range(n):
    B[i] = input(f"Элемент B{i+1, 1}: ")
print(f"Стобец B выглядит так:\n{B}")

#Ввод матрицы или скаляра Q
Q_view = input(f"Q - это скаляр(0) или матрица(1): ")
if int(Q_view) == 0:
    Q = float(input("Введите скаляр Q: "))
    Q = Q * np.eye(n)
    print(f"Скаляр Q выглядит так:\n{Q}")
elif int(Q_view) == 1:
    Q = np.zeros((n, n))
    for i in range(n):
        for j in range(n):
            Q[i][j] = input(f"Элемент Q{i+1, j+1}: ")
    print(f"Матрица Q выглядит так:\n{Q}")

#Ввод матрицы или скаляра R
R_view = input(f"R - это скаляр(0) или матрица(1): ")
if int(R_view) == 0:
    R = float(input("Введите скаляр R: "))
    R = np.array([[R]])
    print(f"Скаляр R выглядит так:\n{R}")
elif int(R_view) == 1:
    R = np.zeros((n, n))
    for i in range(n):
        for j in range(n):
            R[i][j] = input(f"Элемент R{i+1, j+1}: ")
    print(f"Матрица R выглядит так:\n{R}")

#Решение уравнения Риккати:
X = solve_discrete_are(A, B, Q, R)

#Проверка матрицы на симметричность и положительную (неотрицательную) определенность
eig_X = np.linalg.eigvals(X)

print(f'Проверьте матрицу на наблюдаемость!')
obv = int(input(f'Система полностью наблюдаема - 0, Детектируема - 1'))

#Если система полностью наблюдаема, то требуем положительную определенность собственных чисел
if obv == 0:
    test_arr = []
    for i in range(n):
        if eig_X[i] > 0:
            test_arr.append(1)
        else:
            test_arr.append(0)
#Если система детектируема, то требуем неотрицательную определенность собственных чисел
elif obv == 1:
    test_arr = []
    for i in range(n):
        if eig_X[i] >= 0:
            test_arr.append(1)
        else:
            test_arr.append(0)

is_all_one_count = test_arr.count(1) == len(test_arr)
if is_all_one_count:
    print("Решение найдено!")
    print(f"Матрица X:\n {X}")
    print(f"Собственные числа:\n {eig_X}")
else:
    print("Нет решения!")

# матрица оптимальной обратной связи
K = np.linalg.inv(R + B.T @ X @ B) @ (B.T @ X @ A)

#Найдем оптимальное управление U = - (B^T*X*B + R)^-1 * B^T*X*A*x
U = - K 
print("Матрица U:")
print(U)

Ввод матрицы A
Матрица A выглядит так:
[[ 0.  1.]
 [-1.  1.]]
Ввод столбца B
Стобец B выглядит так:
[[0.]
 [1.]]
Матрица Q выглядит так:
[[1. 0.]
 [0. 0.]]
Скаляр R выглядит так:
[[1.]]
Проверьте матрицу на наблюдаемость!
Решение найдено!
Матрица X:
 [[ 1.65398566 -0.48586827]
 [-0.48586827  1.89005364]]
Собственные числа:
 [1.27201965 2.27201965]
Матрица U:
[[ 0.65398566 -0.48586827]]
